---
# Dotfiles Configuration (https://galaxy.ansible.com/geerlingguy/dotfiles/)

dotfiles_repo_owner: "dotCipher"
dotfiles_repo_name: "dotfiles"

## The git repository to use for retrieving dotfiles. Dotfiles should generally be laid out within the
##  root directory of the repository.
dotfiles_repo: "git@github.com:{{ dotfiles_repo_owner }}/{{ dotfiles_repo_name }}.git"

## Add the hostkey for the repo url if not already added.
##  If ssh_opts contains "-o StrictHostKeyChecking=no", this parameter is ignored.
dotfiles_repo_accept_hostkey: no

## The home directory where dotfiles will be linked. Generally, the default should work, but in some circumstances,
##  or when running the role as sudo on behalf of another user, you may want to specify the full path.
dotfiles_home: "~"

## Which files from the dotfiles repository should be linked to the dotfiles_home.
dotfiles_files:
  # Bash
  - .bash_aliases
  - .bash_env
  - .bash_profile
  - .bashrc
  # Fish shell
  - .config/fish/config.fish
  - .config/fish/aliases.fish
  - .config/fish/functions/gi.fish
  - .config/fish/functions/get-cert.fish
  - .config/fish/functions/git-prune.fish
  - .config/fish/functions/git-prune-all.fish
  - .config/fish/functions/gppr.fish
  # GnuPG
  - .gnupg/gpg-agent.conf
  # Vim
  - .vimrc
  # Git
  - .gitconfig

