---
## Keyboard
# Set key repeat rate (Off: 300000, Slow: 120, Fast: 2)
Keyboard_KeyRepeat: 2
# Set delay until repeat, in milliseconds (Long: 120, Short: 15)
Keyboard_InitialKeyRepeat: 15

## Login
Login_guestAccess: NO

# OSX Defaults Configuration (https://galaxy.ansible.com/lafarer/osx-defaults/)

## AppStore
AppStore_Enabled: true                          # Enable AppStore configuration
AppStore_AutomaticCheckEnabled: true            # Automatically check for updates
AppStore_AutomaticDownload: true                # Download newly available updates in the background
AppStore_AutoUpdate: true                       # Install app updates
AppStore_AutoUpdateRestartRequired: true        # Install OSX updates
AppStore_ConfigDataInstall: true                # Install system data files
AppStore_CriticalUpdateInstall: true            # Install security updates
AppStore_ScheduleFrequency: 1                    # Check for software updates (in days)
#AppStore_ShowDebugMenu: false                    # Show debug menu

## Bluetooth
#Bluetooth_Enabled: false                         # Enable Bluetooth configuration
#Bluetooth_ShowInMenuBar: "false"                 # Show Bluetooth in menu bar

## Dashboard
Dashboard_Enabled: true                         # Enable Dashboard configuration
Dashboard_McxDisabled: true                      # Disable Dashboard
Dashboard_EnabledState: 1                        # Dashboard state (1: Off, 2: As Space, 3: As Overlay)
Dashboard_DontShowAsSpace: true                  # Don’t show Dashboard as a Space
#Dashboard_DevMode: false                         # Enable Dashboard dev mode (allows keeping widgets on the desktop)

## DateTime
DateTime_Enabled: true                          # Enable Date Time configuration
DateTime_TimeZone: "America/Los_Angeles"             # Set the timezone; see `systemsetup -listtimezones` for other values
DateTime_AutomaticDateTime: "on"                 # Set date and time automatically (on | off)
DateTime_TimeServer: "time.google.com"            # Set time server
DateTime_AutomaticTimeZone: true                 # Set time zome automatically using current location
DateTime_DateFormat: "HH:mm:ss"                      # Menu bar clock format ("h:mm": Default, "HH": Use a 24-hour clock, "a": Show AM/PM, "ss": Display the time with seconds
DateTime_FlashDateSeparators: false              # Flash the time separators
DateTime_IsAnalog: false                         # Analog menu bar clock

## Displays
Displays_Enabled: true                          # Enable Displays configuration
Displays_AutomaticallyAdjustBrightness: false    # Automatically adjust brightness
Displays_ShowInMenuBarIfPresent: true            # Show mirroring options in the menu bar when available
Displays_AppleFontSmoothing: 2                   # Subpixel font rendering on non-Apple LCDs (0:Disabled, 1:Minimal, 2:Medium, 3:Smoother, 4:Strong)
Displays_DisplayResolutionEnabled: true          # Enable HiDPI display modes (requires restart)

## Dock
Dock_Enabled: true                              # Enable Dock configuration
Dock_TileSize: 64                                # Dock size
Dock_Magnification: false                         # Dock magnification
#Dock_LargeSize: 128                              # Icon size of magnified Dock items
Dock_Orientation: "bottom"                       # Dock orientation: left, bottom, right
#Dock_MinEffect: "genie"                          # Minimization effect: genie, scale, suck
#Dock_AppleActionOnDoubleClick: "Maximize"        # Double-click a window's title title bar to: None, Minimize, Maximize
#Dock_MinimizeToApplication: false                # Minimize windows appliction into icon (true, false)
#Dock_LaunchAnim: true                            # Animate opening applications
Dock_Autohide: true                             # Automatically hide and show the Dock
Dock_ShowProcessIndicators: true                 # Show indicator for open applications
#Dock_ShowHidden: false                           # Display translucent Dock icons for hidden applications

## General
General_Enabled: true                           # Enable General configuration
General_AppleAquaColorVariant: 1                 # Set appearance (1: Blue, 6: Graphite)
General_AppleInterfaceStyle: "Dark"                  # Use Dark menu bar and Dock (Empty or "Dark")
#General_AutoHideMenuBar: false                   # Automatically hide and show the menu bar
General_AppleHighlightColor: "Blue"              # Highlight color (Red, Orange, Yellow, Green, Blue, Purple, Pink, Brown, Graphite)
#General_SidebarIconSize: 1                       # Sidebar icon size (Small: 1, Medium: 2, Large: 3)
General_AppleShowScrollBars: "Automatic"         # Scroll bar visibility (WhenScrolling, Automatic, Always)
General_AppleScrollerPagingBehavior: 1           # Click in the scrollbar to (0: Jump to the next page, 1: Jump to the spot that's clicked)
General_NSCloseAlwaysConfirmsChanges: false      # Ask to keep changes when closing documents
General_CloseWindowsWhenQuittingApp: true       # Close windows when quitting an application
General_NSScrollAnimationEnabled: true           # Smooth scrolling (Disable on older Macs)

## iCloud
ICloud_Enabled: false                            # Enable iCloud configuration
ICloud_NSDocumentSaveNewDocumentsToCloud: false   # Save to iCloud by default

## Language Region
#LanguageRegion_Enabled: false                    # Enable Language and Region configuration
#LanguageRegion_Languages: [ "en", "fr" ]         # Preferred languages (in order of preference e.g. [ "en", "fr" ])
LanguageRegion_Locale: "en_US@currency=USD"      # Locale and Currency (United States : en_US@currency=USD, Great Britian : en_GB@currency=EUR)
#LanguageRegion_MeasurementUnits: "Inches"        # Measure Units (Inches, Centimeters)
#LanguageRegion_Force24HourTime: "true"           # Force 12/24 hour time
#LanguageRegion_MetricUnits: "false"              # Set Metric Units

## Mission Control
MissionControl_Enabled: true                    # Enable Mission Control configuration
MissionControl_MruSpaces: false                  # Automatically rearrange Spaces based on most recent use
MissionControl_SwitchOnActivate: true            # When switching to an application, switch to a Space with open windows for the application
MissionControl_GroupByApp: true                  # Group windows by application in Mission Control
MissionControl_SpansDisplays: true               # Displays have separate Spaces
