---
- name: Update package manager cache
  apt:
    update_cache: yes
    force_apt_get: yes
  when:
    - ansible_pkg_mgr == "apt"
  become_user: root

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  when:
    - ansible_pkg_mgr == "apt"
  become_user: root