---
- name: Ensure all unwanted items are removed from Dock
  shell: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: "{{ dockitems_to_remove | default([]) }}"

- name: Check if wanted items in Dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist | default([]) }}"

- name: Ensure correct positioning order for wanted Dock items
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: "{{ dockitems_to_persist | default([]) }}"
