---
- name: "Download v{{ terraform_version }} of terraform on OSX"
  unarchive:
    src: "{{ terraform_download_url_prefix }}/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
  become_user: root
  when:
    - ansible_distribution == "MacOSX"

- name: "Download v{{ terraform_version }} of terraform on Linux / WSL"
  unarchive:
    src: "{{ terraform_download_url_prefix }}/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: yes
  become_user: root
  when:
    - ansible_system == "Linux"