---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - ../configs/fish-shell.yml

  handlers:
    - import_tasks: ../handlers/fish-shell.yml

  tasks:
    # Become root user for editing through symlink on OSX (see https://stackoverflow.com/questions/33396807/ansible-lineinfile-give-an-error-with-etc-hosts)
    - include_tasks: ../tasks/fish-shell.yml
#      become_user: root
