---
- name: "Lookup fish shell path"
  command: "which fish"
  register: fish_shell_path

- name: "Ensure shell line exists in /etc/shells"
  lineinfile:
    path: /etc/shells
    state: present
    line: "{{ fish_shell_path.stdout }}"

- name: "Set fish shell for {{ lookup('env','USER') }}"
  user:
    name: "{{ ansible_user }}"
    shell: "{{ fish_shell_path.stdout }}"
  become_user: root

- name: "Check for existing oh-my-fish install"
  stat:
    path: "{{ ansible_env.HOME }}/.local/share/omf"
  register: oh_my_fish_dir

- name: "Setup oh-my-fish plugin management framework"
  block:
    - name: "Download oh-my-fish installer"
      get_url:
        url: https://get.oh-my.fish
        dest: "{{ ansible_env.HOME }}/.oh-my-fish-install.sh"
        owner: "{{ lookup('env','USER') }}"
        mode: u+rwx
    - name: "Install oh-my-fish"
      command: "{{ ansible_env.HOME }}/.oh-my-fish-install.sh --noninteractive --yes"
    - name: "Clean up oh-my-fish installer"
      file:
        path: "{{ ansible_env.HOME }}/.oh-my-fish-install.sh"
        state: absent
  when: oh_my_fish_dir.stat.exists == False
  become_user: "{{ lookup('env','USER') }}"

- name: "Install oh-my-fish plugins and themes"
  raw: "{{ fish_shell_path.stdout }} -c \"omf install {{ item|quote }}\""
  with_items: "{{ oh_my_fish_extensions }}"
  become_user: "{{ lookup('env','USER') }}"
  notify: "Update oh-my-fish"
