---
- hosts: all
  connection: local
  become: true
  become_user: "{{ lookup('env','USER') }}"

  vars_files:
    - ../../configs/osx/dock.yml

  tasks:
    - include_tasks: ../../tasks/osx/dock.yml
